package = "omega"
version = "0.1.0"
lua = ">=5.1"

[description]
summary = "Personal neovim plugin"
maintainer = "iSplasher"
labels = [ "" ]
license = "MIT"

[dependencies]
# Add your dependencies here
# `busted = ">=2.0"`

[run]
args = [ "src/main.lua" ]

[build]
type = "builtin"